name: Build Docker images for C++

on: [push]

jobs:
  build-cpp-common:
    name: build cpp-common
    runs-on: [self-hosted, heavy-build]
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_NAME: cpp-common
            IMAGE_TAG: 22.04
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        uses: ./.github/actions/docker-build-base
        with:
          image: ${{ matrix.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
          workdir: ${{ matrix.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}

  build-gcc:
    name: build gcc
    runs-on: [self-hosted, heavy-build]
    needs: build-cpp-common
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_NAME: gcc
            IMAGE_TAG: 11-22.04
            PARENT_ARTIFACT: cpp-common-22.04
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        uses: ./.github/actions/docker-build-child
        with:
          parentArtifact: ${{ matrix.PARENT_ARTIFACT }}
          image: ${{ matrix.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
          workdir: ${{ matrix.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}

  build-clang:
    name: build clang
    runs-on: [self-hosted, heavy-build]
    needs: build-cpp-common
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_NAME: clang
            IMAGE_TAG: 14-22.04
            PARENT_ARTIFACT: cpp-common-22.04
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        uses: ./.github/actions/docker-build-child
        with:
          parentArtifact: ${{ matrix.PARENT_ARTIFACT }}
          image: ${{ matrix.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
          workdir: ${{ matrix.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}

  deploy:
    runs-on: [self-hosted, heavy-build]
    if: github.ref_name == 'main'
    needs: build-gcc
    strategy:
      matrix:
        include:
          - IMAGE_NAME: gcc
            IMAGE_TAG: 11-22.04
          - IMAGE_NAME: clang
            IMAGE_TAG: 14-22.04
    steps:
      - name: docker push
        uses: ./.github/actions/docker-push
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: ${{ matrix.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
